apiVersion: v1
kind: Service
metadata:
  name: kubecube-audit-nodeport
  namespace: kubecube-system
spec:
  type: NodePort
  selector:
    kubecube.io/app: kubecube-audit
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30008